os:
  - linux

language: php

dist: trusty

php:
  - "8.1"
  - "8.0"
  - "7.4"
  - "7.3"

before_install:
  - composer selfupdate

before_script:
  - composer install

script:
  - ./vendor/phpunit/phpunit/phpunit

notifications:
  emails:
    - tomk79@gmail.com
  on_success: always
  on_failure: always
